Simulation exercise done in JNB

In [2]:
import numpy as np
import pandas as pd
np.random.seed(123)



# 1 How likely is it that you roll doubles when rolling two dice?

In [44]:
n_trials = nrows = 50000000
n_dice = ncols = 2
np.random.seed(123)

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
#rolls

In [45]:
doubles_count = 0
for roll in rolls:
    if roll[0] == roll[1]:
        doubles_count += 1

In [46]:
probability_of_doubles = doubles_count / len(rolls)
probability_of_doubles

0.16670292

In [25]:
equal_to = [2,4,6,8,10,12]
# nrow.sum() in equal_to     # this is to set true
#np.sum([[0, 1], [0, 5]], axis=1)

roll_sum = np.sum(rolls, axis=1)
roll_sum

array([ 9,  8,  6,  7,  4,  3,  3,  3, 10,  6])

In [ ]:
# lambda?
# 

roll_sum in 

In [12]:
#showing without the reshape
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice)
rolls

array([1, 5, 2, 4, 3, 5, 3, 5, 1, 6, 1, 2, 4, 5, 5, 5, 2, 6, 4, 3])

In [6]:
# newarr = a[np.array([3, 1, 2 ])] 

newarr1 = rolls[np.array([0], n_trials, n_dice)]
newarr1

ValueError: only 2 non-keyword arguments accepted

In [13]:
newarr2 = rolls[np.array([1])]

 -- 2
 If you flip 8 coins,
 what is the probability of getting exactly 3 heads? 
     - array n_flips must == 3 [not < or >]
     
 What is the probability of getting more than 3 heads?
     - array n_flips must > 3

In [26]:
n_flips = nrows = 10
n_coins = ncols = 8
np.random.seed(123)

flips = np.random.choice([0,1], n_flips * n_coins).reshape(nrows, ncols)
flips

array([[0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 1]])

In [27]:
flip_sum = np.sum(flips, axis=1)
flip_sum

array([2, 5, 4, 3, 4, 4, 3, 4, 2, 4])

-- 3
There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
Assuming that Codeup randomly selects an alumni to put on a billboard,
what are the odds that the two billboards I drive past both have data science students on them?

assumption - ea cohort is same number

web_dev = 3 choices = [1,2,3]     vs.  ds_co = 1 choices [4]

chance_pool = [1



-- 4
Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine.
If on monday the machine is restocked with 17 poptart packages, 
how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [ ]:
-- 5
Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- If a man and woman are chosen at random, P(woman taller than man)?

-- 6
When installing anaconda on a student's computer, 
   there's a 1 in 250 chance that the download is corrupted 
   and 
   the installation fails. 
   
What are the odds that after having 50 students download anaconda, no one has an installation issue?
    100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?
How likely is it that 450 students all download anaconda without an issue?

-- 7
There's a 70% chance on any given day that there will be at least one food truck at Travis Park.
However, you haven't seen a food truck there in 3 days.
How unlikely is this?

How likely is it that a food truck will show up sometime this week?

-- 8
If 23 people are in the same room, 
what are the odds that two of them share a birthday? 
What if it's 20 people? 40?